[[redirects]]
  from = "/api/vi/video/upload"
  to = "https://easy-split-api.onrender.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
